---
name: Armando
surname: Ocampo
position: "Data Scientist - General Practitioner - Ms Biochemistry"
address: "Universidad Autónoma del Estado de Morelos, Universidad Nacional Autónoma de México"
phone: +52 735 206 6804
email: "armando.odelvalle19@gmail.com"
github: armandoODV19
linkedin: Armando Ocampo del Valle
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::moderncv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Work experience

 * 2018-2019 Professor of mathematics and statistics.
 * 2020-2022 General Practitioner.
 * 2022 Data analyst & Data scientists, Universidad Autónoma del Estado de Morelos.

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "General Practitioner", "2012-2019", "Universidad Autonoma del Estado de Morelos", "Morelos, Mexico",
  "Master of Biochemistry", "2020-2022", "Universidad Nacional Autonoma de Mexico", "Morelos, Mexico"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```


# Some stuff about me

 * Languages: Spanish (native speaker), English (fluent speaker).
 * Programming languages: R, SQL.
 * Data analysis trainning.
 * Excel & Tableau project management
